# Generated by Django 4.2 on 2023-08-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper', models.CharField(blank=True, max_length=250, verbose_name='Верхняя часть')),
                ('medium', models.CharField(blank=True, max_length=250, verbose_name='Средняя часть')),
                ('lower', models.CharField(blank=True, max_length=250, verbose_name='Нижняя часть')),
            ],
        ),
    ]
