# Generated by Django 4.2 on 2023-08-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Название пункта меню')),
                ('ordering', models.PositiveIntegerField(unique=True, verbose_name='Порядковый номер')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
